<?php

namespace FCPHP\TodoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TodoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TodoRepository extends EntityRepository
{
	public function findIncompleteTodos()
	{
		return $this->findBy(array(
			'completed' => 0
		));
	}

	public function findCompletedTodos()
	{
		return $this->findBy(array(
			'completed' => 1
		));
	}
}
